version: 0.1

phases:
    build:
      commands:
        - npm install
        - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - "Simon Fairall Resume.pdf"
    - styles/*
    - images/*
    - dist/bundle.js
