version: 0.1

phases:
    build:
      commands:
        - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - "Simon Fairall Resume.pdf"
    - styles/*
    - images/*
